#!/Users/anandhd/Downloads/current/AI_project/final_project/.venv-mac/bin/python3.14
import sys
from plotly.io._kaleido import plotly_get_chrome
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(plotly_get_chrome())
